### ISSUE TITLE
Support `nodejs@20` expression

### ISSUE THREAD

**Issue by bytemain** [version-fox/version-fox-plugins#14]
![CleanShot 2024-02-20 at 18 13 59@2x](https://github.com/version-fox/version-fox-plugins/assets/13938334/9a9be539-bd3d-42e2-8049-4aedc9c4ced9)

If user input 20, we should get the latest version for node 20 and then install it

**Comment by aooohan** [comment]
It's also easy to implement, are you interested in raising a PR？

**Comment by bytemain** [comment]
yes, I will try it later
