### ISSUE TITLE
some version checksum not detected

### ISSUE THREAD

**Issue by padulkemid** [version-fox/version-fox-plugins#39]
when I take a look at the code, it seems fine, this came from `kotlin`, I tried to download manually the plugin using the same `DownloadUrl` and manually configured the version to what I wanted but it returns this error:
![Screenshot 2024-03-20 at 9 55 16 PM](https://github.com/version-fox/version-fox-plugins/assets/1876018/57bfb8db-1191-4a0f-88d7-a5a4541ca56f)

is there anything wrong with github checksum returned and getting parsed here?

strangely, it works in `kotlin` v1.9.0 and up

**Comment by padulkemid** [comment]
this was on the recent version of `vfox` -> v0.2.6

**Comment by padulkemid** [comment]
fixed by commenting this code:
![Screenshot 2024-03-21 at 3 33 57 AM](https://github.com/version-fox/version-fox-plugins/assets/1876018/67e6591f-87ef-4056-8a9e-252d01e738b8)

proof:
![Screenshot 2024-03-21 at 3 33 24 AM](https://github.com/version-fox/version-fox-plugins/assets/1876018/ce1bf315-5273-476e-9f72-eafd552ba31a)

it seems `kotlin` RC from github are not returning `.sha256` checksum? but it auto skips verify from `vfox` original pre-install check

**Comment by padulkemid** [comment]
imma uncomment this once again, thanks @aooohan if there's any other I'll post here again, it seems I can't find out whats happening in the `lua` or `go` source code

**Comment by aooohan** [comment]
> it seems kotlin RC from github are not returning .sha256 checksum? 

Yes. Earlier than 1.9.0 do not provide `.sha256` files.

As you commented code snippet, we just don't need to get checksum if earlier than 1.9.0, which can fix this.

**Comment by ahai-code** [comment]
Thanks for pointing this issue out! We have fixed it, you can use `vfox update kotlin` to upgrade to latest to try again.
